/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "PlatformTypes.h"

#define RCC_BASE 	0x40021000
#define GPIOA_BASE	0x40010800

#define RCC_APB2NR	*(volatile uint32*)(RCC_BASE + 0x18)

#define GPIOA_CRH	*(volatile uint32*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR	*(volatile uint32*)(GPIOA_BASE + 0x0C)

#define RCC_IOPAEN (1<<2)

typedef union
{
	uint16 all_bits;
	struct
	{
		uint16 reserved:13;
		uint16 P13:1;
	}PIN;
}PORT;

volatile PORT* PORTA = (volatile PORT*)(GPIOA_BASE + 0X0C);
int main(void)
{

	RCC_APB2NR |= RCC_IOPAEN; //Enables GPIOA
	GPIOA_CRH &= ~(0xf << (4 * 5));
	GPIOA_CRH |=  (0X2 << (4 * 5));


    /* Loop forever */
	while(1)
	{
		PORTA->PIN.P13 ^= 1;;
		for(int i = 0; i < 500000; i++);
	}
}
